apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: ClusterIP
  selector:
    app: service2
  ports:
  - name: flask
    port: 5002
    targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 3
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: stratcastor/rand2:build-0
        ports:
          - containerPort: 5002
